### ISSUE TITLE
HTTP POST requests exceeding 1500 byte cannot be obtained

### ISSUE THREAD

**Issue by ttgml** [sonuauti/Android-Web-Server#3]
When I use the http client to initiate an HTTP POST request, if the size of the first packet is greater than 1500 bytes, I can't get the full POST data.

**Comment by sonuauti** [comment]
increase byte buffer at
**byte[] data = new byte[1500];**

to your required length

**Comment by 2minchul** [comment]
It's a more good idea to allocate an array as many as `Content-Length`

**Comment by ttgml** [comment]
done
