### ISSUE TITLE
Can We Access in Android?

### ISSUE THREAD

**Issue by Sba-Stuff** [sonuauti/Android-Web-Server#5]
I want to run html5 game in android. My Theme is that I run localhost using your library, then open index.html in Webview.

So what I did is created assets folder and add all the game code there.

Then did what you said.

TinyWebServer.startServer("localhost",9000, "/web/public_html");

If I change "/web/public_html" to "android_asset/", will it work?

**Comment by sonuauti** [comment]
it should work, if not you can copy the files from android asset dir to internal storage on app load.

**Comment by Sba-Stuff** [comment]
Ok, Thank you :)
